@baseUrl = {{host}}
@token = {{jwtTokenAdmin}}

### Create new movie
POST {{baseUrl}}/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Avengers: Endgame",
    "vietnameseTitle": "Biệt Đội Siêu Anh Hùng: Hồi Kết",
    "description": "After the devastating events of Avengers: Infinity War...",
    "posterUrl": "https://example.com/poster.jpg",
    "bannerUrl": "https://example.com/banner.jpg",
    "trailerUrl": "https://youtube.com/watch?v=TcMBFSGVi1c",
    "duration": 181,
    "releaseDate": "2023-07-01",
    "genre": ["Action", "Adventure", "Drama"],
    "director": "Anthony Russo, Joe Russo",
    "actors": ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    "language": "English",
    "rating": "C13"
}

### Update movie
PUT {{baseUrl}}/movies/684027317225707556860ce2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "now_showing",
    "endDate": "2024-01-01"
}

### Delete movie
DELETE {{baseUrl}}/movies/684027317225707556860ce2
Authorization: Bearer {{token}} 